name: CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ejecutar tests backend
        run: |
          cd BACKEND/demo/demo
          mvn test

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar frontend
        run: |
          cd FRONTEND/cliente-react
          npm install

      - name: Instalar navegadores Playwright
        run: |
          cd FRONTEND/cliente-react
          npx playwright install --with-deps

      - name: Instalar wait-on
        run: npm install -g wait-on

      - name: Ejecutar tests frontend
        run: |
          cd FRONTEND/cliente-react
          npm run dev &
          wait-on http://localhost:5173
          npx playwright test